### PR TITLE
adding stop_layer to minnie

### PR DESCRIPTION
**Pull request by fcollman**

### CODE REVIEW

**Comment by akhileshh** [comment]
I don't think this is necessary, `leaves_only=True` should take care of it

**Comment by fcollman** [comment]
I thought this function signature was a bit weird, but i have to pass nodes_only=True in order to use the stop_layer/return_layers  functionality yes?

```  
def get_subgraph(
        self,
        node_id_or_ids: typing.Union[np.uint64, typing.Iterable],
        bbox: typing.Optional[typing.Sequence[typing.Sequence[int]]] = None,
        bbox_is_coordinate: bool = False,
        return_layers: typing.List = [2],
        nodes_only: bool = False,
        edges_only: bool = False,
        leaves_only: bool = False,
        n_threads: int = 1,
    ) -> typing.Tuple[typing.Dict, typing.Dict, Edges]:
        if nodes_only:
            return self.get_subgraph_nodes(
                node_id_or_ids, bbox, bbox_is_coordinate, return_layers
            )
        return self.get_subgraph_edges_and_leaves(
            node_id_or_ids, bbox, bbox_is_coordinate, edges_only, leaves_only, n_threads
        )
```

**Comment by akhileshh** [comment]
I see what you mean, it is necessary for leaves of multiple nodes. But you can get rid of it in `handle_leaves`.

**Comment by akhileshh** [comment]
actually maybe not, is the main goal here only leaves or intermediate layers are to be included in the usecase?

**Comment by fcollman** [comment]
the idea is that sometimes people want to get lvl2_ids only (like in meshing but unrelated to meshes), or they might want to get level7 nodes of a root id (due to skips you can't gauruntee, but you could say level 3 or above.

**Comment by akhileshh** [comment]
Wouldn't it be better to refactor children endpoint in that case? "leaves" specifically refers to L1 and might get confusing

**Comment by akhileshh** [comment]
I'm open to either solutions, should be good as long as its documented well

**Comment by akhileshh** [comment]
will take care of this in #261

**Pull request closed without merging**
