### PR TITLE
fix(ingest): Ignore missing edges from empty chunks

### PR DESCRIPTION
**Pull request by nkemnitz**

### CODE REVIEW

**Comment by sdorkenw** [comment]
@akhileshh could you take a look at why this build is failing?

**Comment by akhileshh** [comment]
This is fine, the tests are being run in zetta environments because this is a fork, zetta doesn't have access to secrets in seunglab account. Although I think we can get rid of the `docker-login` action, don't think it is necessary now that we're pulling from dockerhub.

**Comment by akhileshh** [comment]
#415

**Comment by sdorkenw** [comment]
Could you rebase this on main - I just merged #415

**Comment by akhileshh** [comment]
@sdorkenw  We should merge this. Only affects agglomeration reading code, which isn't used in the tests.

**Pull request merged**
