### PR TITLE
get leaves fix + configurable row count

### PR DESCRIPTION
**Pull request by fcollman**
This adds a configuration for max_row_count in the bigtable client (and changes the default to 1000).

It also has a fix for get_leaves with stop_layer which was not working becuase the format wasn't consisstent in unpacking the resullts of the bigtable query.  Using the flatten option simplified thing.  One can look up what level things are from via the nodeId.

### CODE REVIEW

**Comment by sdorkenw** [comment]
Looks good to me

**Review by akhileshh — APPROVED** [review]
looks good

**Comment by nkemnitz** [comment]
Why the change from 20,000 to 1,000 rows? Isn't sending up to 20x more requests going to be noticeably slower?

**Comment by akhileshh** [comment]
Something has probably changed on bigtable server side, higher batch sizes increased latency by a lot, should be linear but it is not

test run by @sdorkenw , batch size and time
```
1000 - 0.3s
2000 - 0.62s
4000 - 1.68s
8000 - 5.69s
16000 - 21.0s
```

**Comment by nkemnitz** [comment]
Oh wow, that's huge. Thanks for the numbers!

**Comment by sdorkenw** [comment]
For clarification: These are get_roots calls. The number in the table above is the number of supervoxels that went into it.
Not sure what changed here... Getting ready to delete some tables on the cluster to see if that impacts performance (as it might change the distribution of rows across the nodes). I am thinking of raising this with the Google BigTable team because this should not scale worse than linear (verified in a notebook that it is actually the call to BigTable and nothing on our end).

**Pull request merged**
