### PR TITLE
fix: dracopy changes

### PR DESCRIPTION
**Pull request by akhileshh**

### CODE REVIEW

**Comment by william-silversmith** [comment]
Thanks Akhilesh! I think there are still some difference from this one: https://github.com/seung-lab/PyChunkedGraph/pull/384/files Can you explain why there were different choices made?

Also, I would recommend setting `DracoPy~=1.0.0` which will allow upgrades until the next major version (breaking change). This will help prevent surprises. I'm not planning on any but I think it's good practice.

**Comment by akhileshh** [comment]
I had no idea this was already done. Sven must have forgotten about it and asked me to look into this.
Anyway I also made changes so cloudfiles was used instead, tested locally and remeshing worked fine.
Will update the `requirements.txt`

**Comment by akhileshh** [comment]
> Can you explain why there were different choices made?

As for differences, I don't know if Manuel had any particular reasons put the assert statement so I thought best to keep it.
Do you think it is not necessary?

**Comment by william-silversmith** [comment]
Looks good. Thanks for converting the storage too. I want to fully remove it from CloudVolume at some point in the future.

**Review by william-silversmith — APPROVED** [review]

**Pull request merged**
