### PR TITLE
Operation details endpoint

### PR DESCRIPTION
**Pull request by kaikue**
Returns the list of added or removed edges for a given operation ID. More info about the operation can be added to this as needed.

### CODE REVIEW

**Comment by kaikue** [comment]
I don't know why those old commits are in there, I swear I based the branch off master... Git eludes me yet again

**Comment by akhileshh** [comment]
maybe change `/table/<table_id>/operation_details` to `/table/<table_id>/operation/<operation_id>` ? more convenient than query params IMO

**Comment by sdorkenw** [comment]
Agree with that in general for single ids. It might be better to go one step further and accept a list of operation ids; need to use a query parameter then after all.

**Comment by akhileshh** [comment]
could do both `/table/<table_id>/operations/<operation_id>` and `/table/<table_id>/operations?ids=[1,2,3]`
first check for path param and then query param

and to reduce payload for array input, filter by fields 
`/table/<table_id>/operations?ids=[1,2,3,...]&fields=['user','timestamp','type']`

**Comment by kaikue** [comment]
Ok, per discussion with Sven I changed it to:
`/table/<table_id>/operation_details?operation_ids=1111,2222,3333`
and the response to:
```
{
    '1111': {...},
    '2222': {...},
    '3333': {...}
}
```

**Comment by akhileshh** [comment]
I think with square brackets it can be parsed as json array, no need to split and convert to `int`

**Comment by sdorkenw** [comment]
@kaikue looking into this some more, I agree with @akhileshh that parsing this without the `.split` would be better. I will still merge this to keep things going but please make a new PR with this change later this week

**Pull request merged**
